package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActiveGame generated by hbm2java
 */
@Entity
@Table(name = "active_game", catalog = "megalodondb")
public class ActiveGame implements java.io.Serializable {

	private ActiveGameId id;
	private Games games;
	private Users users;

	public ActiveGame() {
	}

	public ActiveGame(ActiveGameId id, Games games, Users users) {
		this.id = id;
		this.games = games;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idUsers", column = @Column(name = "Id_users", nullable = false)),
			@AttributeOverride(name = "idGame", column = @Column(name = "Id_game", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "Status")) })
	public ActiveGameId getId() {
		return this.id;
	}

	public void setId(ActiveGameId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_game", nullable = false, insertable = false, updatable = false)
	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_users", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
