package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BillDetail generated by hbm2java
 */
@Entity
@Table(name = "bill_detail", catalog = "megalodondb")
public class BillDetail implements java.io.Serializable {

	private Integer idBillDetail;
	private Bill bill;
	private Games games;
	private Long price;

	public BillDetail() {
	}

	public BillDetail(Bill bill, Games games, Long price) {
		this.bill = bill;
		this.games = games;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_bill_detail", unique = true, nullable = false)
	public Integer getIdBillDetail() {
		return this.idBillDetail;
	}

	public void setIdBillDetail(Integer idBillDetail) {
		this.idBillDetail = idBillDetail;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_bill")
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_game")
	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}

	@Column(name = "Price", precision = 18, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

}
