package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GameCategory generated by hbm2java
 */
@Entity
@Table(name = "game_category", catalog = "megalodondb")
public class GameCategory implements java.io.Serializable {

	private GameCategoryId id;
	private Category category;
	private Games games;

	public GameCategory() {
	}

	public GameCategory(GameCategoryId id, Category category, Games games) {
		this.id = id;
		this.category = category;
		this.games = games;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idGame", column = @Column(name = "Id_game", nullable = false)),
			@AttributeOverride(name = "idCategory", column = @Column(name = "Id_category", nullable = false)) })
	public GameCategoryId getId() {
		return this.id;
	}

	public void setId(GameCategoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_category", nullable = false, insertable = false, updatable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_game", nullable = false, insertable = false, updatable = false)
	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}

}
