package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReplyCommentGame generated by hbm2java
 */
@Entity
@Table(name = "reply_comment_game", catalog = "megalodondb")
public class ReplyCommentGame implements java.io.Serializable {

	private Integer idReplyCommentGame;
	private CommentGame commentGame;
	private Integer idUsers;
	private String contentComment;

	public ReplyCommentGame() {
	}

	public ReplyCommentGame(CommentGame commentGame, Integer idUsers, String contentComment) {
		this.commentGame = commentGame;
		this.idUsers = idUsers;
		this.contentComment = contentComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_reply_comment_game", unique = true, nullable = false)
	public Integer getIdReplyCommentGame() {
		return this.idReplyCommentGame;
	}

	public void setIdReplyCommentGame(Integer idReplyCommentGame) {
		this.idReplyCommentGame = idReplyCommentGame;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_comment_game")
	public CommentGame getCommentGame() {
		return this.commentGame;
	}

	public void setCommentGame(CommentGame commentGame) {
		this.commentGame = commentGame;
	}

	@Column(name = "Id_users")
	public Integer getIdUsers() {
		return this.idUsers;
	}

	public void setIdUsers(Integer idUsers) {
		this.idUsers = idUsers;
	}

	@Column(name = "Content_comment", length = 150)
	public String getContentComment() {
		return this.contentComment;
	}

	public void setContentComment(String contentComment) {
		this.contentComment = contentComment;
	}

}
