package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReplyCommentBlog generated by hbm2java
 */
@Entity
@Table(name = "reply_comment_blog", catalog = "megalodondb")
public class ReplyCommentBlog implements java.io.Serializable {

	private Integer idReplyCommentBlog;
	private CommentBlog commentBlog;
	private int idUsers;
	private String contentComment;

	public ReplyCommentBlog() {
	}

	public ReplyCommentBlog(CommentBlog commentBlog, int idUsers) {
		this.commentBlog = commentBlog;
		this.idUsers = idUsers;
	}

	public ReplyCommentBlog(CommentBlog commentBlog, int idUsers, String contentComment) {
		this.commentBlog = commentBlog;
		this.idUsers = idUsers;
		this.contentComment = contentComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_reply_comment_blog", unique = true, nullable = false)
	public Integer getIdReplyCommentBlog() {
		return this.idReplyCommentBlog;
	}

	public void setIdReplyCommentBlog(Integer idReplyCommentBlog) {
		this.idReplyCommentBlog = idReplyCommentBlog;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_commnet_blog", nullable = false)
	public CommentBlog getCommentBlog() {
		return this.commentBlog;
	}

	public void setCommentBlog(CommentBlog commentBlog) {
		this.commentBlog = commentBlog;
	}

	@Column(name = "Id_users", nullable = false)
	public int getIdUsers() {
		return this.idUsers;
	}

	public void setIdUsers(int idUsers) {
		this.idUsers = idUsers;
	}

	@Column(name = "Content_comment", length = 150)
	public String getContentComment() {
		return this.contentComment;
	}

	public void setContentComment(String contentComment) {
		this.contentComment = contentComment;
	}

}
