package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SystemId generated by hbm2java
 */
@Embeddable
public class SystemId implements java.io.Serializable {

	private int dowloadSystem;
	private int viewsSystem;
	private Date date;

	public SystemId() {
	}

	public SystemId(int dowloadSystem, int viewsSystem, Date date) {
		this.dowloadSystem = dowloadSystem;
		this.viewsSystem = viewsSystem;
		this.date = date;
	}

	@Column(name = "Dowload_system", nullable = false)
	public int getDowloadSystem() {
		return this.dowloadSystem;
	}

	public void setDowloadSystem(int dowloadSystem) {
		this.dowloadSystem = dowloadSystem;
	}

	@Column(name = "views_system", nullable = false)
	public int getViewsSystem() {
		return this.viewsSystem;
	}

	public void setViewsSystem(int viewsSystem) {
		this.viewsSystem = viewsSystem;
	}

	@Column(name = "Date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SystemId))
			return false;
		SystemId castOther = (SystemId) other;

		return (this.getDowloadSystem() == castOther.getDowloadSystem())
				&& (this.getViewsSystem() == castOther.getViewsSystem())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDowloadSystem();
		result = 37 * result + this.getViewsSystem();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
