package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TokenUser generated by hbm2java
 */
@Entity
@Table(name = "token_user", catalog = "megalodondb")
public class TokenUser implements java.io.Serializable {

	private Integer idTokenUsers;
	private Users users;
	private String valueTokenUsers;
	private Date date;

	public TokenUser() {
	}

	public TokenUser(Users users) {
		this.users = users;
	}

	public TokenUser(Users users, String valueTokenUsers, Date date) {
		this.users = users;
		this.valueTokenUsers = valueTokenUsers;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_token_users", unique = true, nullable = false)
	public Integer getIdTokenUsers() {
		return this.idTokenUsers;
	}

	public void setIdTokenUsers(Integer idTokenUsers) {
		this.idTokenUsers = idTokenUsers;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_users", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "value_token_users", length = 45)
	public String getValueTokenUsers() {
		return this.valueTokenUsers;
	}

	public void setValueTokenUsers(String valueTokenUsers) {
		this.valueTokenUsers = valueTokenUsers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
