package com.web.demo.entity;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "megalodondb")
public class Users implements java.io.Serializable {

	private Integer idUsers;
	private Role role;
	private String nameUsers;
	private String usernameUsers;
	private String passwordUsers;
	private String emailUsers;
	private String phoneUsers;
	private String imageUsers;
	private String addressUsers;
	private Date dateOfBirthday;
	private Integer gender;
	private Integer status;
	private Set<TokenUser> tokenUsers = new HashSet<TokenUser>(0);
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<Blog> blogs = new HashSet<Blog>(0);
	private Set<CommentBlog> commentBlogs = new HashSet<CommentBlog>(0);
	private Set<CommentGame> commentGames = new HashSet<CommentGame>(0);
	private Set<ActiveGame> activeGames = new HashSet<ActiveGame>(0);

	public Users() {
	}

	public Users(Role role, String usernameUsers, String passwordUsers, String emailUsers) {
		this.role = role;
		this.usernameUsers = usernameUsers;
		this.passwordUsers = passwordUsers;
		this.emailUsers = emailUsers;
	}

	public Users(Role role, String nameUsers, String usernameUsers, String passwordUsers, String emailUsers,
			String phoneUsers, String imageUsers, String addressUsers, Date dateOfBirthday, Integer gender,
			Integer status, Set<TokenUser> tokenUsers, Set<Bill> bills, Set<Blog> blogs, Set<CommentBlog> commentBlogs,
			Set<CommentGame> commentGames, Set<ActiveGame> activeGames) {
		this.role = role;
		this.nameUsers = nameUsers;
		this.usernameUsers = usernameUsers;
		this.passwordUsers = passwordUsers;
		this.emailUsers = emailUsers;
		this.phoneUsers = phoneUsers;
		this.imageUsers = imageUsers;
		this.addressUsers = addressUsers;
		this.dateOfBirthday = dateOfBirthday;
		this.gender = gender;
		this.status = status;
		this.tokenUsers = tokenUsers;
		this.bills = bills;
		this.blogs = blogs;
		this.commentBlogs = commentBlogs;
		this.commentGames = commentGames;
		this.activeGames = activeGames;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_users", unique = true, nullable = false)
	public Integer getIdUsers() {
		return this.idUsers;
	}

	public void setIdUsers(Integer idUsers) {
		this.idUsers = idUsers;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_role", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "Name_users", length = 45)
	public String getNameUsers() {
		return this.nameUsers;
	}

	public void setNameUsers(String nameUsers) {
		this.nameUsers = nameUsers;
	}

	@Column(name = "Username_users", nullable = false, length = 45)
	public String getUsernameUsers() {
		return this.usernameUsers;
	}

	public void setUsernameUsers(String usernameUsers) {
		this.usernameUsers = usernameUsers;
	}

	@Column(name = "Password_users", nullable = false, length = 45)
	public String getPasswordUsers() {
		return this.passwordUsers;
	}

	public void setPasswordUsers(String passwordUsers) {
		this.passwordUsers = passwordUsers;
	}

	@Column(name = "Email_users", nullable = false, length = 45)
	public String getEmailUsers() {
		return this.emailUsers;
	}

	public void setEmailUsers(String emailUsers) {
		this.emailUsers = emailUsers;
	}

	@Column(name = "Phone_users", length = 45)
	public String getPhoneUsers() {
		return this.phoneUsers;
	}

	public void setPhoneUsers(String phoneUsers) {
		this.phoneUsers = phoneUsers;
	}

	@Column(name = "Image_users", length = 45)
	public String getImageUsers() {
		return this.imageUsers;
	}

	public void setImageUsers(String imageUsers) {
		this.imageUsers = imageUsers;
	}

	@Column(name = "Address_users", length = 45)
	public String getAddressUsers() {
		return this.addressUsers;
	}

	public void setAddressUsers(String addressUsers) {
		this.addressUsers = addressUsers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_of_birthday", length = 10)
	public Date getDateOfBirthday() {
		return this.dateOfBirthday;
	}

	public void setDateOfBirthday(Date dateOfBirthday) {
		this.dateOfBirthday = dateOfBirthday;
	}

	@Column(name = "Gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
	public Set<TokenUser> getTokenUsers() {
		return this.tokenUsers;
	}

	public void setTokenUsers(Set<TokenUser> tokenUsers) {
		this.tokenUsers = tokenUsers;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
	public Set<Blog> getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set<Blog> blogs) {
		this.blogs = blogs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
	public Set<CommentBlog> getCommentBlogs() {
		return this.commentBlogs;
	}

	public void setCommentBlogs(Set<CommentBlog> commentBlogs) {
		this.commentBlogs = commentBlogs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
	public Set<CommentGame> getCommentGames() {
		return this.commentGames;
	}

	public void setCommentGames(Set<CommentGame> commentGames) {
		this.commentGames = commentGames;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
	public Set<ActiveGame> getActiveGames() {
		return this.activeGames;
	}

	public void setActiveGames(Set<ActiveGame> activeGames) {
		this.activeGames = activeGames;
	}

}
